package es.aalvarez.modelica.model;

public class ArticuloInformeJuridico {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_articulo_ij.id
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_articulo_ij.lex
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String lex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_articulo_ij.articulo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String articulo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_articulo_ij.epigrafe_articulo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String epigrafeArticulo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_articulo_ij.contenido_articulo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String contenidoArticulo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_articulo_ij.id
	 * @return  the value of modlic_articulo_ij.id
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_articulo_ij.id
	 * @param id  the value for modlic_articulo_ij.id
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_articulo_ij.lex
	 * @return  the value of modlic_articulo_ij.lex
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getLex() {
		return lex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_articulo_ij.lex
	 * @param lex  the value for modlic_articulo_ij.lex
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setLex(String lex) {
		this.lex = lex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_articulo_ij.articulo
	 * @return  the value of modlic_articulo_ij.articulo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getArticulo() {
		return articulo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_articulo_ij.articulo
	 * @param articulo  the value for modlic_articulo_ij.articulo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setArticulo(String articulo) {
		this.articulo = articulo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_articulo_ij.epigrafe_articulo
	 * @return  the value of modlic_articulo_ij.epigrafe_articulo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getEpigrafeArticulo() {
		return epigrafeArticulo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_articulo_ij.epigrafe_articulo
	 * @param epigrafeArticulo  the value for modlic_articulo_ij.epigrafe_articulo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setEpigrafeArticulo(String epigrafeArticulo) {
		this.epigrafeArticulo = epigrafeArticulo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_articulo_ij.contenido_articulo
	 * @return  the value of modlic_articulo_ij.contenido_articulo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getContenidoArticulo() {
		return contenidoArticulo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_articulo_ij.contenido_articulo
	 * @param contenidoArticulo  the value for modlic_articulo_ij.contenido_articulo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setContenidoArticulo(String contenidoArticulo) {
		this.contenidoArticulo = contenidoArticulo;
	}
}