package es.aalvarez.modelica.model;

import java.util.ArrayList;
import java.util.List;

public class ArticuloInformeJuridicoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public ArticuloInformeJuridicoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andLexIsNull() {
			addCriterion("lex is null");
			return (Criteria) this;
		}

		public Criteria andLexIsNotNull() {
			addCriterion("lex is not null");
			return (Criteria) this;
		}

		public Criteria andLexEqualTo(String value) {
			addCriterion("lex =", value, "lex");
			return (Criteria) this;
		}

		public Criteria andLexNotEqualTo(String value) {
			addCriterion("lex <>", value, "lex");
			return (Criteria) this;
		}

		public Criteria andLexGreaterThan(String value) {
			addCriterion("lex >", value, "lex");
			return (Criteria) this;
		}

		public Criteria andLexGreaterThanOrEqualTo(String value) {
			addCriterion("lex >=", value, "lex");
			return (Criteria) this;
		}

		public Criteria andLexLessThan(String value) {
			addCriterion("lex <", value, "lex");
			return (Criteria) this;
		}

		public Criteria andLexLessThanOrEqualTo(String value) {
			addCriterion("lex <=", value, "lex");
			return (Criteria) this;
		}

		public Criteria andLexLike(String value) {
			addCriterion("lex like", value, "lex");
			return (Criteria) this;
		}

		public Criteria andLexNotLike(String value) {
			addCriterion("lex not like", value, "lex");
			return (Criteria) this;
		}

		public Criteria andLexIn(List<String> values) {
			addCriterion("lex in", values, "lex");
			return (Criteria) this;
		}

		public Criteria andLexNotIn(List<String> values) {
			addCriterion("lex not in", values, "lex");
			return (Criteria) this;
		}

		public Criteria andLexBetween(String value1, String value2) {
			addCriterion("lex between", value1, value2, "lex");
			return (Criteria) this;
		}

		public Criteria andLexNotBetween(String value1, String value2) {
			addCriterion("lex not between", value1, value2, "lex");
			return (Criteria) this;
		}

		public Criteria andArticuloIsNull() {
			addCriterion("articulo is null");
			return (Criteria) this;
		}

		public Criteria andArticuloIsNotNull() {
			addCriterion("articulo is not null");
			return (Criteria) this;
		}

		public Criteria andArticuloEqualTo(String value) {
			addCriterion("articulo =", value, "articulo");
			return (Criteria) this;
		}

		public Criteria andArticuloNotEqualTo(String value) {
			addCriterion("articulo <>", value, "articulo");
			return (Criteria) this;
		}

		public Criteria andArticuloGreaterThan(String value) {
			addCriterion("articulo >", value, "articulo");
			return (Criteria) this;
		}

		public Criteria andArticuloGreaterThanOrEqualTo(String value) {
			addCriterion("articulo >=", value, "articulo");
			return (Criteria) this;
		}

		public Criteria andArticuloLessThan(String value) {
			addCriterion("articulo <", value, "articulo");
			return (Criteria) this;
		}

		public Criteria andArticuloLessThanOrEqualTo(String value) {
			addCriterion("articulo <=", value, "articulo");
			return (Criteria) this;
		}

		public Criteria andArticuloLike(String value) {
			addCriterion("articulo like", value, "articulo");
			return (Criteria) this;
		}

		public Criteria andArticuloNotLike(String value) {
			addCriterion("articulo not like", value, "articulo");
			return (Criteria) this;
		}

		public Criteria andArticuloIn(List<String> values) {
			addCriterion("articulo in", values, "articulo");
			return (Criteria) this;
		}

		public Criteria andArticuloNotIn(List<String> values) {
			addCriterion("articulo not in", values, "articulo");
			return (Criteria) this;
		}

		public Criteria andArticuloBetween(String value1, String value2) {
			addCriterion("articulo between", value1, value2, "articulo");
			return (Criteria) this;
		}

		public Criteria andArticuloNotBetween(String value1, String value2) {
			addCriterion("articulo not between", value1, value2, "articulo");
			return (Criteria) this;
		}

		public Criteria andEpigrafeArticuloIsNull() {
			addCriterion("epigrafe_articulo is null");
			return (Criteria) this;
		}

		public Criteria andEpigrafeArticuloIsNotNull() {
			addCriterion("epigrafe_articulo is not null");
			return (Criteria) this;
		}

		public Criteria andEpigrafeArticuloEqualTo(String value) {
			addCriterion("epigrafe_articulo =", value, "epigrafeArticulo");
			return (Criteria) this;
		}

		public Criteria andEpigrafeArticuloNotEqualTo(String value) {
			addCriterion("epigrafe_articulo <>", value, "epigrafeArticulo");
			return (Criteria) this;
		}

		public Criteria andEpigrafeArticuloGreaterThan(String value) {
			addCriterion("epigrafe_articulo >", value, "epigrafeArticulo");
			return (Criteria) this;
		}

		public Criteria andEpigrafeArticuloGreaterThanOrEqualTo(String value) {
			addCriterion("epigrafe_articulo >=", value, "epigrafeArticulo");
			return (Criteria) this;
		}

		public Criteria andEpigrafeArticuloLessThan(String value) {
			addCriterion("epigrafe_articulo <", value, "epigrafeArticulo");
			return (Criteria) this;
		}

		public Criteria andEpigrafeArticuloLessThanOrEqualTo(String value) {
			addCriterion("epigrafe_articulo <=", value, "epigrafeArticulo");
			return (Criteria) this;
		}

		public Criteria andEpigrafeArticuloLike(String value) {
			addCriterion("epigrafe_articulo like", value, "epigrafeArticulo");
			return (Criteria) this;
		}

		public Criteria andEpigrafeArticuloNotLike(String value) {
			addCriterion("epigrafe_articulo not like", value,
					"epigrafeArticulo");
			return (Criteria) this;
		}

		public Criteria andEpigrafeArticuloIn(List<String> values) {
			addCriterion("epigrafe_articulo in", values, "epigrafeArticulo");
			return (Criteria) this;
		}

		public Criteria andEpigrafeArticuloNotIn(List<String> values) {
			addCriterion("epigrafe_articulo not in", values, "epigrafeArticulo");
			return (Criteria) this;
		}

		public Criteria andEpigrafeArticuloBetween(String value1, String value2) {
			addCriterion("epigrafe_articulo between", value1, value2,
					"epigrafeArticulo");
			return (Criteria) this;
		}

		public Criteria andEpigrafeArticuloNotBetween(String value1,
				String value2) {
			addCriterion("epigrafe_articulo not between", value1, value2,
					"epigrafeArticulo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table modlic_articulo_ij
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 08 22:00:32 CEST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}