package es.aalvarez.modelica.model;

import java.io.Serializable;
import java.util.Date;

public class Expediente implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.id
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.num_entrada
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer numEntrada;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.fecha_entrada
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Date fechaEntrada;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.tipo_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String tipoExpediente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.subtipo_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String subtipoExpediente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer expediente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.anyo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer anyo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.interesado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String interesado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.nif_interesado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String nifInteresado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.representante
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String representante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.nif_representante
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String nifRepresentante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.estado_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String estadoExpediente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.fase_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer faseExpediente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.providencia_fecha
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Date providenciaFecha;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.providencia_firmante
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String providenciaFirmante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.providencia_firmante_cargo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String providenciaFirmanteCargo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.providencia_firmante_delegacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String providenciaFirmanteDelegacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.providencia_tecnico_asignado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String providenciaTecnicoAsignado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.providencia_cod_id
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String providenciaCodId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.ruta_providencia
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String rutaProvidencia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.ruta_inf_tecnico
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String rutaInfTecnico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.ruta_inf_juridico
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String rutaInfJuridico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.ruta_resolucion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String rutaResolucion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.actuacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String actuacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.emplazamiento
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String emplazamiento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.ref_catastral
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String refCatastral;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.doc_tecnico
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String docTecnico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.fecha_visado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String fechaVisado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.num_visado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String numVisado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.num_colegiado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String numColegiado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.redactor
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String redactor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.licencia_base
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String licenciaBase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.expediente_finalizado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Boolean expedienteFinalizado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.inf_tecnico_fecha
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Date infTecnicoFecha;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.inf_tecnico_firmante
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String infTecnicoFirmante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.aux01
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String aux01;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.aux02
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String aux02;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.aux03
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String aux03;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.aux04
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String aux04;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.aux05
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String aux05;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.aux06
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String aux06;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.aux07
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String aux07;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.aux08
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String aux08;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.aux09
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String aux09;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.aux10
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String aux10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_expediente.observaciones
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String observaciones;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.id
	 * @return  the value of modlic_expediente.id
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.id
	 * @param id  the value for modlic_expediente.id
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.num_entrada
	 * @return  the value of modlic_expediente.num_entrada
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getNumEntrada() {
		return numEntrada;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.num_entrada
	 * @param numEntrada  the value for modlic_expediente.num_entrada
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setNumEntrada(Integer numEntrada) {
		this.numEntrada = numEntrada;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.fecha_entrada
	 * @return  the value of modlic_expediente.fecha_entrada
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Date getFechaEntrada() {
		return fechaEntrada;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.fecha_entrada
	 * @param fechaEntrada  the value for modlic_expediente.fecha_entrada
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setFechaEntrada(Date fechaEntrada) {
		this.fechaEntrada = fechaEntrada;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.tipo_expediente
	 * @return  the value of modlic_expediente.tipo_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getTipoExpediente() {
		return tipoExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.tipo_expediente
	 * @param tipoExpediente  the value for modlic_expediente.tipo_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setTipoExpediente(String tipoExpediente) {
		this.tipoExpediente = tipoExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.subtipo_expediente
	 * @return  the value of modlic_expediente.subtipo_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getSubtipoExpediente() {
		return subtipoExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.subtipo_expediente
	 * @param subtipoExpediente  the value for modlic_expediente.subtipo_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setSubtipoExpediente(String subtipoExpediente) {
		this.subtipoExpediente = subtipoExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.expediente
	 * @return  the value of modlic_expediente.expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getExpediente() {
		return expediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.expediente
	 * @param expediente  the value for modlic_expediente.expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setExpediente(Integer expediente) {
		this.expediente = expediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.anyo
	 * @return  the value of modlic_expediente.anyo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getAnyo() {
		return anyo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.anyo
	 * @param anyo  the value for modlic_expediente.anyo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setAnyo(Integer anyo) {
		this.anyo = anyo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.interesado
	 * @return  the value of modlic_expediente.interesado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getInteresado() {
		return interesado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.interesado
	 * @param interesado  the value for modlic_expediente.interesado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setInteresado(String interesado) {
		this.interesado = interesado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.nif_interesado
	 * @return  the value of modlic_expediente.nif_interesado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getNifInteresado() {
		return nifInteresado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.nif_interesado
	 * @param nifInteresado  the value for modlic_expediente.nif_interesado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setNifInteresado(String nifInteresado) {
		this.nifInteresado = nifInteresado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.representante
	 * @return  the value of modlic_expediente.representante
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getRepresentante() {
		return representante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.representante
	 * @param representante  the value for modlic_expediente.representante
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setRepresentante(String representante) {
		this.representante = representante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.nif_representante
	 * @return  the value of modlic_expediente.nif_representante
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getNifRepresentante() {
		return nifRepresentante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.nif_representante
	 * @param nifRepresentante  the value for modlic_expediente.nif_representante
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setNifRepresentante(String nifRepresentante) {
		this.nifRepresentante = nifRepresentante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.estado_expediente
	 * @return  the value of modlic_expediente.estado_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getEstadoExpediente() {
		return estadoExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.estado_expediente
	 * @param estadoExpediente  the value for modlic_expediente.estado_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setEstadoExpediente(String estadoExpediente) {
		this.estadoExpediente = estadoExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.fase_expediente
	 * @return  the value of modlic_expediente.fase_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getFaseExpediente() {
		return faseExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.fase_expediente
	 * @param faseExpediente  the value for modlic_expediente.fase_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setFaseExpediente(Integer faseExpediente) {
		this.faseExpediente = faseExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.providencia_fecha
	 * @return  the value of modlic_expediente.providencia_fecha
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Date getProvidenciaFecha() {
		return providenciaFecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.providencia_fecha
	 * @param providenciaFecha  the value for modlic_expediente.providencia_fecha
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setProvidenciaFecha(Date providenciaFecha) {
		this.providenciaFecha = providenciaFecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.providencia_firmante
	 * @return  the value of modlic_expediente.providencia_firmante
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getProvidenciaFirmante() {
		return providenciaFirmante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.providencia_firmante
	 * @param providenciaFirmante  the value for modlic_expediente.providencia_firmante
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setProvidenciaFirmante(String providenciaFirmante) {
		this.providenciaFirmante = providenciaFirmante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.providencia_firmante_cargo
	 * @return  the value of modlic_expediente.providencia_firmante_cargo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getProvidenciaFirmanteCargo() {
		return providenciaFirmanteCargo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.providencia_firmante_cargo
	 * @param providenciaFirmanteCargo  the value for modlic_expediente.providencia_firmante_cargo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setProvidenciaFirmanteCargo(String providenciaFirmanteCargo) {
		this.providenciaFirmanteCargo = providenciaFirmanteCargo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.providencia_firmante_delegacion
	 * @return  the value of modlic_expediente.providencia_firmante_delegacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getProvidenciaFirmanteDelegacion() {
		return providenciaFirmanteDelegacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.providencia_firmante_delegacion
	 * @param providenciaFirmanteDelegacion  the value for modlic_expediente.providencia_firmante_delegacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setProvidenciaFirmanteDelegacion(
			String providenciaFirmanteDelegacion) {
		this.providenciaFirmanteDelegacion = providenciaFirmanteDelegacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.providencia_tecnico_asignado
	 * @return  the value of modlic_expediente.providencia_tecnico_asignado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getProvidenciaTecnicoAsignado() {
		return providenciaTecnicoAsignado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.providencia_tecnico_asignado
	 * @param providenciaTecnicoAsignado  the value for modlic_expediente.providencia_tecnico_asignado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setProvidenciaTecnicoAsignado(String providenciaTecnicoAsignado) {
		this.providenciaTecnicoAsignado = providenciaTecnicoAsignado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.providencia_cod_id
	 * @return  the value of modlic_expediente.providencia_cod_id
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getProvidenciaCodId() {
		return providenciaCodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.providencia_cod_id
	 * @param providenciaCodId  the value for modlic_expediente.providencia_cod_id
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setProvidenciaCodId(String providenciaCodId) {
		this.providenciaCodId = providenciaCodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.ruta_providencia
	 * @return  the value of modlic_expediente.ruta_providencia
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getRutaProvidencia() {
		return rutaProvidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.ruta_providencia
	 * @param rutaProvidencia  the value for modlic_expediente.ruta_providencia
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setRutaProvidencia(String rutaProvidencia) {
		this.rutaProvidencia = rutaProvidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.ruta_inf_tecnico
	 * @return  the value of modlic_expediente.ruta_inf_tecnico
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getRutaInfTecnico() {
		return rutaInfTecnico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.ruta_inf_tecnico
	 * @param rutaInfTecnico  the value for modlic_expediente.ruta_inf_tecnico
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setRutaInfTecnico(String rutaInfTecnico) {
		this.rutaInfTecnico = rutaInfTecnico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.ruta_inf_juridico
	 * @return  the value of modlic_expediente.ruta_inf_juridico
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getRutaInfJuridico() {
		return rutaInfJuridico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.ruta_inf_juridico
	 * @param rutaInfJuridico  the value for modlic_expediente.ruta_inf_juridico
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setRutaInfJuridico(String rutaInfJuridico) {
		this.rutaInfJuridico = rutaInfJuridico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.ruta_resolucion
	 * @return  the value of modlic_expediente.ruta_resolucion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getRutaResolucion() {
		return rutaResolucion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.ruta_resolucion
	 * @param rutaResolucion  the value for modlic_expediente.ruta_resolucion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setRutaResolucion(String rutaResolucion) {
		this.rutaResolucion = rutaResolucion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.actuacion
	 * @return  the value of modlic_expediente.actuacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getActuacion() {
		return actuacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.actuacion
	 * @param actuacion  the value for modlic_expediente.actuacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setActuacion(String actuacion) {
		this.actuacion = actuacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.emplazamiento
	 * @return  the value of modlic_expediente.emplazamiento
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getEmplazamiento() {
		return emplazamiento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.emplazamiento
	 * @param emplazamiento  the value for modlic_expediente.emplazamiento
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setEmplazamiento(String emplazamiento) {
		this.emplazamiento = emplazamiento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.ref_catastral
	 * @return  the value of modlic_expediente.ref_catastral
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getRefCatastral() {
		return refCatastral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.ref_catastral
	 * @param refCatastral  the value for modlic_expediente.ref_catastral
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setRefCatastral(String refCatastral) {
		this.refCatastral = refCatastral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.doc_tecnico
	 * @return  the value of modlic_expediente.doc_tecnico
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getDocTecnico() {
		return docTecnico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.doc_tecnico
	 * @param docTecnico  the value for modlic_expediente.doc_tecnico
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setDocTecnico(String docTecnico) {
		this.docTecnico = docTecnico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.fecha_visado
	 * @return  the value of modlic_expediente.fecha_visado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getFechaVisado() {
		return fechaVisado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.fecha_visado
	 * @param fechaVisado  the value for modlic_expediente.fecha_visado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setFechaVisado(String fechaVisado) {
		this.fechaVisado = fechaVisado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.num_visado
	 * @return  the value of modlic_expediente.num_visado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getNumVisado() {
		return numVisado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.num_visado
	 * @param numVisado  the value for modlic_expediente.num_visado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setNumVisado(String numVisado) {
		this.numVisado = numVisado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.num_colegiado
	 * @return  the value of modlic_expediente.num_colegiado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getNumColegiado() {
		return numColegiado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.num_colegiado
	 * @param numColegiado  the value for modlic_expediente.num_colegiado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setNumColegiado(String numColegiado) {
		this.numColegiado = numColegiado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.redactor
	 * @return  the value of modlic_expediente.redactor
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getRedactor() {
		return redactor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.redactor
	 * @param redactor  the value for modlic_expediente.redactor
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setRedactor(String redactor) {
		this.redactor = redactor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.licencia_base
	 * @return  the value of modlic_expediente.licencia_base
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getLicenciaBase() {
		return licenciaBase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.licencia_base
	 * @param licenciaBase  the value for modlic_expediente.licencia_base
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setLicenciaBase(String licenciaBase) {
		this.licenciaBase = licenciaBase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.expediente_finalizado
	 * @return  the value of modlic_expediente.expediente_finalizado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Boolean getExpedienteFinalizado() {
		return expedienteFinalizado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.expediente_finalizado
	 * @param expedienteFinalizado  the value for modlic_expediente.expediente_finalizado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setExpedienteFinalizado(Boolean expedienteFinalizado) {
		this.expedienteFinalizado = expedienteFinalizado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.inf_tecnico_fecha
	 * @return  the value of modlic_expediente.inf_tecnico_fecha
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Date getInfTecnicoFecha() {
		return infTecnicoFecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.inf_tecnico_fecha
	 * @param infTecnicoFecha  the value for modlic_expediente.inf_tecnico_fecha
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setInfTecnicoFecha(Date infTecnicoFecha) {
		this.infTecnicoFecha = infTecnicoFecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.inf_tecnico_firmante
	 * @return  the value of modlic_expediente.inf_tecnico_firmante
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getInfTecnicoFirmante() {
		return infTecnicoFirmante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.inf_tecnico_firmante
	 * @param infTecnicoFirmante  the value for modlic_expediente.inf_tecnico_firmante
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setInfTecnicoFirmante(String infTecnicoFirmante) {
		this.infTecnicoFirmante = infTecnicoFirmante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.aux01
	 * @return  the value of modlic_expediente.aux01
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getAux01() {
		return aux01;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.aux01
	 * @param aux01  the value for modlic_expediente.aux01
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setAux01(String aux01) {
		this.aux01 = aux01;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.aux02
	 * @return  the value of modlic_expediente.aux02
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getAux02() {
		return aux02;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.aux02
	 * @param aux02  the value for modlic_expediente.aux02
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setAux02(String aux02) {
		this.aux02 = aux02;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.aux03
	 * @return  the value of modlic_expediente.aux03
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getAux03() {
		return aux03;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.aux03
	 * @param aux03  the value for modlic_expediente.aux03
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setAux03(String aux03) {
		this.aux03 = aux03;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.aux04
	 * @return  the value of modlic_expediente.aux04
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getAux04() {
		return aux04;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.aux04
	 * @param aux04  the value for modlic_expediente.aux04
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setAux04(String aux04) {
		this.aux04 = aux04;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.aux05
	 * @return  the value of modlic_expediente.aux05
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getAux05() {
		return aux05;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.aux05
	 * @param aux05  the value for modlic_expediente.aux05
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setAux05(String aux05) {
		this.aux05 = aux05;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.aux06
	 * @return  the value of modlic_expediente.aux06
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getAux06() {
		return aux06;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.aux06
	 * @param aux06  the value for modlic_expediente.aux06
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setAux06(String aux06) {
		this.aux06 = aux06;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.aux07
	 * @return  the value of modlic_expediente.aux07
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getAux07() {
		return aux07;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.aux07
	 * @param aux07  the value for modlic_expediente.aux07
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setAux07(String aux07) {
		this.aux07 = aux07;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.aux08
	 * @return  the value of modlic_expediente.aux08
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getAux08() {
		return aux08;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.aux08
	 * @param aux08  the value for modlic_expediente.aux08
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setAux08(String aux08) {
		this.aux08 = aux08;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.aux09
	 * @return  the value of modlic_expediente.aux09
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getAux09() {
		return aux09;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.aux09
	 * @param aux09  the value for modlic_expediente.aux09
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setAux09(String aux09) {
		this.aux09 = aux09;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.aux10
	 * @return  the value of modlic_expediente.aux10
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getAux10() {
		return aux10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.aux10
	 * @param aux10  the value for modlic_expediente.aux10
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setAux10(String aux10) {
		this.aux10 = aux10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_expediente.observaciones
	 * @return  the value of modlic_expediente.observaciones
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getObservaciones() {
		return observaciones;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_expediente.observaciones
	 * @param observaciones  the value for modlic_expediente.observaciones
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -8655235959197428382L;
}