package es.aalvarez.modelica.model;

public class ExpedienteRelacionado {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_exprelacionados.idRelacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer idrelacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_exprelacionados.idExpedienteA
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer idexpedientea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_exprelacionados.idExpedienteB
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer idexpedienteb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_exprelacionados.descripcion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String descripcion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_exprelacionados.idRelacion
	 * @return  the value of modlic_exprelacionados.idRelacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getIdrelacion() {
		return idrelacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_exprelacionados.idRelacion
	 * @param idrelacion  the value for modlic_exprelacionados.idRelacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setIdrelacion(Integer idrelacion) {
		this.idrelacion = idrelacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_exprelacionados.idExpedienteA
	 * @return  the value of modlic_exprelacionados.idExpedienteA
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getIdexpedientea() {
		return idexpedientea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_exprelacionados.idExpedienteA
	 * @param idexpedientea  the value for modlic_exprelacionados.idExpedienteA
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setIdexpedientea(Integer idexpedientea) {
		this.idexpedientea = idexpedientea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_exprelacionados.idExpedienteB
	 * @return  the value of modlic_exprelacionados.idExpedienteB
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getIdexpedienteb() {
		return idexpedienteb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_exprelacionados.idExpedienteB
	 * @param idexpedienteb  the value for modlic_exprelacionados.idExpedienteB
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setIdexpedienteb(Integer idexpedienteb) {
		this.idexpedienteb = idexpedienteb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_exprelacionados.descripcion
	 * @return  the value of modlic_exprelacionados.descripcion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_exprelacionados.descripcion
	 * @param descripcion  the value for modlic_exprelacionados.descripcion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}