package es.aalvarez.modelica.model;

public class Puesto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_puestos.idPuesto
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer idpuesto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_puestos.puesto
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String puesto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_puestos.codPuesto
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String codpuesto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_puestos.departamento
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String departamento;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_puestos.idPuesto
	 * @return  the value of modlic_puestos.idPuesto
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getIdpuesto() {
		return idpuesto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_puestos.idPuesto
	 * @param idpuesto  the value for modlic_puestos.idPuesto
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setIdpuesto(Integer idpuesto) {
		this.idpuesto = idpuesto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_puestos.puesto
	 * @return  the value of modlic_puestos.puesto
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getPuesto() {
		return puesto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_puestos.puesto
	 * @param puesto  the value for modlic_puestos.puesto
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_puestos.codPuesto
	 * @return  the value of modlic_puestos.codPuesto
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getCodpuesto() {
		return codpuesto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_puestos.codPuesto
	 * @param codpuesto  the value for modlic_puestos.codPuesto
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setCodpuesto(String codpuesto) {
		this.codpuesto = codpuesto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_puestos.departamento
	 * @return  the value of modlic_puestos.departamento
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getDepartamento() {
		return departamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_puestos.departamento
	 * @param departamento  the value for modlic_puestos.departamento
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}
}