package es.aalvarez.modelica.model;

import java.util.ArrayList;
import java.util.List;

public class PuestoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public PuestoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdpuestoIsNull() {
			addCriterion("idPuesto is null");
			return (Criteria) this;
		}

		public Criteria andIdpuestoIsNotNull() {
			addCriterion("idPuesto is not null");
			return (Criteria) this;
		}

		public Criteria andIdpuestoEqualTo(Integer value) {
			addCriterion("idPuesto =", value, "idpuesto");
			return (Criteria) this;
		}

		public Criteria andIdpuestoNotEqualTo(Integer value) {
			addCriterion("idPuesto <>", value, "idpuesto");
			return (Criteria) this;
		}

		public Criteria andIdpuestoGreaterThan(Integer value) {
			addCriterion("idPuesto >", value, "idpuesto");
			return (Criteria) this;
		}

		public Criteria andIdpuestoGreaterThanOrEqualTo(Integer value) {
			addCriterion("idPuesto >=", value, "idpuesto");
			return (Criteria) this;
		}

		public Criteria andIdpuestoLessThan(Integer value) {
			addCriterion("idPuesto <", value, "idpuesto");
			return (Criteria) this;
		}

		public Criteria andIdpuestoLessThanOrEqualTo(Integer value) {
			addCriterion("idPuesto <=", value, "idpuesto");
			return (Criteria) this;
		}

		public Criteria andIdpuestoIn(List<Integer> values) {
			addCriterion("idPuesto in", values, "idpuesto");
			return (Criteria) this;
		}

		public Criteria andIdpuestoNotIn(List<Integer> values) {
			addCriterion("idPuesto not in", values, "idpuesto");
			return (Criteria) this;
		}

		public Criteria andIdpuestoBetween(Integer value1, Integer value2) {
			addCriterion("idPuesto between", value1, value2, "idpuesto");
			return (Criteria) this;
		}

		public Criteria andIdpuestoNotBetween(Integer value1, Integer value2) {
			addCriterion("idPuesto not between", value1, value2, "idpuesto");
			return (Criteria) this;
		}

		public Criteria andPuestoIsNull() {
			addCriterion("puesto is null");
			return (Criteria) this;
		}

		public Criteria andPuestoIsNotNull() {
			addCriterion("puesto is not null");
			return (Criteria) this;
		}

		public Criteria andPuestoEqualTo(String value) {
			addCriterion("puesto =", value, "puesto");
			return (Criteria) this;
		}

		public Criteria andPuestoNotEqualTo(String value) {
			addCriterion("puesto <>", value, "puesto");
			return (Criteria) this;
		}

		public Criteria andPuestoGreaterThan(String value) {
			addCriterion("puesto >", value, "puesto");
			return (Criteria) this;
		}

		public Criteria andPuestoGreaterThanOrEqualTo(String value) {
			addCriterion("puesto >=", value, "puesto");
			return (Criteria) this;
		}

		public Criteria andPuestoLessThan(String value) {
			addCriterion("puesto <", value, "puesto");
			return (Criteria) this;
		}

		public Criteria andPuestoLessThanOrEqualTo(String value) {
			addCriterion("puesto <=", value, "puesto");
			return (Criteria) this;
		}

		public Criteria andPuestoLike(String value) {
			addCriterion("puesto like", value, "puesto");
			return (Criteria) this;
		}

		public Criteria andPuestoNotLike(String value) {
			addCriterion("puesto not like", value, "puesto");
			return (Criteria) this;
		}

		public Criteria andPuestoIn(List<String> values) {
			addCriterion("puesto in", values, "puesto");
			return (Criteria) this;
		}

		public Criteria andPuestoNotIn(List<String> values) {
			addCriterion("puesto not in", values, "puesto");
			return (Criteria) this;
		}

		public Criteria andPuestoBetween(String value1, String value2) {
			addCriterion("puesto between", value1, value2, "puesto");
			return (Criteria) this;
		}

		public Criteria andPuestoNotBetween(String value1, String value2) {
			addCriterion("puesto not between", value1, value2, "puesto");
			return (Criteria) this;
		}

		public Criteria andCodpuestoIsNull() {
			addCriterion("codPuesto is null");
			return (Criteria) this;
		}

		public Criteria andCodpuestoIsNotNull() {
			addCriterion("codPuesto is not null");
			return (Criteria) this;
		}

		public Criteria andCodpuestoEqualTo(String value) {
			addCriterion("codPuesto =", value, "codpuesto");
			return (Criteria) this;
		}

		public Criteria andCodpuestoNotEqualTo(String value) {
			addCriterion("codPuesto <>", value, "codpuesto");
			return (Criteria) this;
		}

		public Criteria andCodpuestoGreaterThan(String value) {
			addCriterion("codPuesto >", value, "codpuesto");
			return (Criteria) this;
		}

		public Criteria andCodpuestoGreaterThanOrEqualTo(String value) {
			addCriterion("codPuesto >=", value, "codpuesto");
			return (Criteria) this;
		}

		public Criteria andCodpuestoLessThan(String value) {
			addCriterion("codPuesto <", value, "codpuesto");
			return (Criteria) this;
		}

		public Criteria andCodpuestoLessThanOrEqualTo(String value) {
			addCriterion("codPuesto <=", value, "codpuesto");
			return (Criteria) this;
		}

		public Criteria andCodpuestoLike(String value) {
			addCriterion("codPuesto like", value, "codpuesto");
			return (Criteria) this;
		}

		public Criteria andCodpuestoNotLike(String value) {
			addCriterion("codPuesto not like", value, "codpuesto");
			return (Criteria) this;
		}

		public Criteria andCodpuestoIn(List<String> values) {
			addCriterion("codPuesto in", values, "codpuesto");
			return (Criteria) this;
		}

		public Criteria andCodpuestoNotIn(List<String> values) {
			addCriterion("codPuesto not in", values, "codpuesto");
			return (Criteria) this;
		}

		public Criteria andCodpuestoBetween(String value1, String value2) {
			addCriterion("codPuesto between", value1, value2, "codpuesto");
			return (Criteria) this;
		}

		public Criteria andCodpuestoNotBetween(String value1, String value2) {
			addCriterion("codPuesto not between", value1, value2, "codpuesto");
			return (Criteria) this;
		}

		public Criteria andDepartamentoIsNull() {
			addCriterion("departamento is null");
			return (Criteria) this;
		}

		public Criteria andDepartamentoIsNotNull() {
			addCriterion("departamento is not null");
			return (Criteria) this;
		}

		public Criteria andDepartamentoEqualTo(String value) {
			addCriterion("departamento =", value, "departamento");
			return (Criteria) this;
		}

		public Criteria andDepartamentoNotEqualTo(String value) {
			addCriterion("departamento <>", value, "departamento");
			return (Criteria) this;
		}

		public Criteria andDepartamentoGreaterThan(String value) {
			addCriterion("departamento >", value, "departamento");
			return (Criteria) this;
		}

		public Criteria andDepartamentoGreaterThanOrEqualTo(String value) {
			addCriterion("departamento >=", value, "departamento");
			return (Criteria) this;
		}

		public Criteria andDepartamentoLessThan(String value) {
			addCriterion("departamento <", value, "departamento");
			return (Criteria) this;
		}

		public Criteria andDepartamentoLessThanOrEqualTo(String value) {
			addCriterion("departamento <=", value, "departamento");
			return (Criteria) this;
		}

		public Criteria andDepartamentoLike(String value) {
			addCriterion("departamento like", value, "departamento");
			return (Criteria) this;
		}

		public Criteria andDepartamentoNotLike(String value) {
			addCriterion("departamento not like", value, "departamento");
			return (Criteria) this;
		}

		public Criteria andDepartamentoIn(List<String> values) {
			addCriterion("departamento in", values, "departamento");
			return (Criteria) this;
		}

		public Criteria andDepartamentoNotIn(List<String> values) {
			addCriterion("departamento not in", values, "departamento");
			return (Criteria) this;
		}

		public Criteria andDepartamentoBetween(String value1, String value2) {
			addCriterion("departamento between", value1, value2, "departamento");
			return (Criteria) this;
		}

		public Criteria andDepartamentoNotBetween(String value1, String value2) {
			addCriterion("departamento not between", value1, value2,
					"departamento");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table modlic_puestos
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table modlic_puestos
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 25 11:13:42 CET 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}