package es.aalvarez.modelica.model;

import java.util.Date;

public class TramiteActivoXExpediente {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.id
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.num_entrada
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer numEntrada;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.fecha_entrada
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Date fechaEntrada;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.tipo_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String tipoExpediente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer expediente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.anyo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer anyo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.interesado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String interesado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.nif_interesado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String nifInteresado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.estado_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String estadoExpediente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.fase_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer faseExpediente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.actuacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String actuacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.emplazamiento
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String emplazamiento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.ref_catastral
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String refCatastral;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.expediente_finalizado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Boolean expedienteFinalizado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.idTramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer idtramite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.cod_modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer codModlicExpediente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.fecha_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Date fechaTramite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.descripcion_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String descripcionTramite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.tramite_asignado_a
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String tramiteAsignadoA;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.tramite_activo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Boolean tramiteActivo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_traxexpedienteview.estado_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String estadoTramite;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.id
	 * @return  the value of modlic_traxexpedienteview.id
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.id
	 * @param id  the value for modlic_traxexpedienteview.id
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.num_entrada
	 * @return  the value of modlic_traxexpedienteview.num_entrada
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getNumEntrada() {
		return numEntrada;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.num_entrada
	 * @param numEntrada  the value for modlic_traxexpedienteview.num_entrada
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setNumEntrada(Integer numEntrada) {
		this.numEntrada = numEntrada;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.fecha_entrada
	 * @return  the value of modlic_traxexpedienteview.fecha_entrada
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Date getFechaEntrada() {
		return fechaEntrada;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.fecha_entrada
	 * @param fechaEntrada  the value for modlic_traxexpedienteview.fecha_entrada
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setFechaEntrada(Date fechaEntrada) {
		this.fechaEntrada = fechaEntrada;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.tipo_expediente
	 * @return  the value of modlic_traxexpedienteview.tipo_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getTipoExpediente() {
		return tipoExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.tipo_expediente
	 * @param tipoExpediente  the value for modlic_traxexpedienteview.tipo_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setTipoExpediente(String tipoExpediente) {
		this.tipoExpediente = tipoExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.expediente
	 * @return  the value of modlic_traxexpedienteview.expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getExpediente() {
		return expediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.expediente
	 * @param expediente  the value for modlic_traxexpedienteview.expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setExpediente(Integer expediente) {
		this.expediente = expediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.anyo
	 * @return  the value of modlic_traxexpedienteview.anyo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getAnyo() {
		return anyo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.anyo
	 * @param anyo  the value for modlic_traxexpedienteview.anyo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setAnyo(Integer anyo) {
		this.anyo = anyo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.interesado
	 * @return  the value of modlic_traxexpedienteview.interesado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getInteresado() {
		return interesado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.interesado
	 * @param interesado  the value for modlic_traxexpedienteview.interesado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setInteresado(String interesado) {
		this.interesado = interesado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.nif_interesado
	 * @return  the value of modlic_traxexpedienteview.nif_interesado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getNifInteresado() {
		return nifInteresado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.nif_interesado
	 * @param nifInteresado  the value for modlic_traxexpedienteview.nif_interesado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setNifInteresado(String nifInteresado) {
		this.nifInteresado = nifInteresado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.estado_expediente
	 * @return  the value of modlic_traxexpedienteview.estado_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getEstadoExpediente() {
		return estadoExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.estado_expediente
	 * @param estadoExpediente  the value for modlic_traxexpedienteview.estado_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setEstadoExpediente(String estadoExpediente) {
		this.estadoExpediente = estadoExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.fase_expediente
	 * @return  the value of modlic_traxexpedienteview.fase_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getFaseExpediente() {
		return faseExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.fase_expediente
	 * @param faseExpediente  the value for modlic_traxexpedienteview.fase_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setFaseExpediente(Integer faseExpediente) {
		this.faseExpediente = faseExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.actuacion
	 * @return  the value of modlic_traxexpedienteview.actuacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getActuacion() {
		return actuacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.actuacion
	 * @param actuacion  the value for modlic_traxexpedienteview.actuacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setActuacion(String actuacion) {
		this.actuacion = actuacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.emplazamiento
	 * @return  the value of modlic_traxexpedienteview.emplazamiento
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getEmplazamiento() {
		return emplazamiento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.emplazamiento
	 * @param emplazamiento  the value for modlic_traxexpedienteview.emplazamiento
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setEmplazamiento(String emplazamiento) {
		this.emplazamiento = emplazamiento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.ref_catastral
	 * @return  the value of modlic_traxexpedienteview.ref_catastral
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getRefCatastral() {
		return refCatastral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.ref_catastral
	 * @param refCatastral  the value for modlic_traxexpedienteview.ref_catastral
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setRefCatastral(String refCatastral) {
		this.refCatastral = refCatastral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.expediente_finalizado
	 * @return  the value of modlic_traxexpedienteview.expediente_finalizado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Boolean getExpedienteFinalizado() {
		return expedienteFinalizado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.expediente_finalizado
	 * @param expedienteFinalizado  the value for modlic_traxexpedienteview.expediente_finalizado
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setExpedienteFinalizado(Boolean expedienteFinalizado) {
		this.expedienteFinalizado = expedienteFinalizado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.idTramite
	 * @return  the value of modlic_traxexpedienteview.idTramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getIdtramite() {
		return idtramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.idTramite
	 * @param idtramite  the value for modlic_traxexpedienteview.idTramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setIdtramite(Integer idtramite) {
		this.idtramite = idtramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.cod_modlic_expediente
	 * @return  the value of modlic_traxexpedienteview.cod_modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getCodModlicExpediente() {
		return codModlicExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.cod_modlic_expediente
	 * @param codModlicExpediente  the value for modlic_traxexpedienteview.cod_modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setCodModlicExpediente(Integer codModlicExpediente) {
		this.codModlicExpediente = codModlicExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.fecha_tramite
	 * @return  the value of modlic_traxexpedienteview.fecha_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Date getFechaTramite() {
		return fechaTramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.fecha_tramite
	 * @param fechaTramite  the value for modlic_traxexpedienteview.fecha_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setFechaTramite(Date fechaTramite) {
		this.fechaTramite = fechaTramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.descripcion_tramite
	 * @return  the value of modlic_traxexpedienteview.descripcion_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getDescripcionTramite() {
		return descripcionTramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.descripcion_tramite
	 * @param descripcionTramite  the value for modlic_traxexpedienteview.descripcion_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setDescripcionTramite(String descripcionTramite) {
		this.descripcionTramite = descripcionTramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.tramite_asignado_a
	 * @return  the value of modlic_traxexpedienteview.tramite_asignado_a
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getTramiteAsignadoA() {
		return tramiteAsignadoA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.tramite_asignado_a
	 * @param tramiteAsignadoA  the value for modlic_traxexpedienteview.tramite_asignado_a
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setTramiteAsignadoA(String tramiteAsignadoA) {
		this.tramiteAsignadoA = tramiteAsignadoA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.tramite_activo
	 * @return  the value of modlic_traxexpedienteview.tramite_activo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Boolean getTramiteActivo() {
		return tramiteActivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.tramite_activo
	 * @param tramiteActivo  the value for modlic_traxexpedienteview.tramite_activo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setTramiteActivo(Boolean tramiteActivo) {
		this.tramiteActivo = tramiteActivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_traxexpedienteview.estado_tramite
	 * @return  the value of modlic_traxexpedienteview.estado_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getEstadoTramite() {
		return estadoTramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_traxexpedienteview.estado_tramite
	 * @param estadoTramite  the value for modlic_traxexpedienteview.estado_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setEstadoTramite(String estadoTramite) {
		this.estadoTramite = estadoTramite;
	}
}