package es.aalvarez.modelica.model;

import java.util.Date;

public class TramiteExpediente {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_tramites.idTramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer idtramite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_tramites.cod_modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Integer codModlicExpediente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_tramites.fecha_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Date fechaTramite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_tramites.descripcion_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String descripcionTramite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_tramites.tramite_asignado_a
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String tramiteAsignadoA;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_tramites.tramite_activo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Boolean tramiteActivo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_tramites.estado_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String estadoTramite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_tramites.incluir_en_indice
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Boolean incluirEnIndice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_tramites.fecha_modificacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private Date fechaModificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column modlic_tramites.ip_cliente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	private String ipCliente;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_tramites.idTramite
	 * @return  the value of modlic_tramites.idTramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getIdtramite() {
		return idtramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_tramites.idTramite
	 * @param idtramite  the value for modlic_tramites.idTramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setIdtramite(Integer idtramite) {
		this.idtramite = idtramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_tramites.cod_modlic_expediente
	 * @return  the value of modlic_tramites.cod_modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Integer getCodModlicExpediente() {
		return codModlicExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_tramites.cod_modlic_expediente
	 * @param codModlicExpediente  the value for modlic_tramites.cod_modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setCodModlicExpediente(Integer codModlicExpediente) {
		this.codModlicExpediente = codModlicExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_tramites.fecha_tramite
	 * @return  the value of modlic_tramites.fecha_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Date getFechaTramite() {
		return fechaTramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_tramites.fecha_tramite
	 * @param fechaTramite  the value for modlic_tramites.fecha_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setFechaTramite(Date fechaTramite) {
		this.fechaTramite = fechaTramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_tramites.descripcion_tramite
	 * @return  the value of modlic_tramites.descripcion_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getDescripcionTramite() {
		return descripcionTramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_tramites.descripcion_tramite
	 * @param descripcionTramite  the value for modlic_tramites.descripcion_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setDescripcionTramite(String descripcionTramite) {
		this.descripcionTramite = descripcionTramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_tramites.tramite_asignado_a
	 * @return  the value of modlic_tramites.tramite_asignado_a
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getTramiteAsignadoA() {
		return tramiteAsignadoA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_tramites.tramite_asignado_a
	 * @param tramiteAsignadoA  the value for modlic_tramites.tramite_asignado_a
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setTramiteAsignadoA(String tramiteAsignadoA) {
		this.tramiteAsignadoA = tramiteAsignadoA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_tramites.tramite_activo
	 * @return  the value of modlic_tramites.tramite_activo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Boolean getTramiteActivo() {
		return tramiteActivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_tramites.tramite_activo
	 * @param tramiteActivo  the value for modlic_tramites.tramite_activo
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setTramiteActivo(Boolean tramiteActivo) {
		this.tramiteActivo = tramiteActivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_tramites.estado_tramite
	 * @return  the value of modlic_tramites.estado_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getEstadoTramite() {
		return estadoTramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_tramites.estado_tramite
	 * @param estadoTramite  the value for modlic_tramites.estado_tramite
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setEstadoTramite(String estadoTramite) {
		this.estadoTramite = estadoTramite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_tramites.incluir_en_indice
	 * @return  the value of modlic_tramites.incluir_en_indice
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Boolean getIncluirEnIndice() {
		return incluirEnIndice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_tramites.incluir_en_indice
	 * @param incluirEnIndice  the value for modlic_tramites.incluir_en_indice
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setIncluirEnIndice(Boolean incluirEnIndice) {
		this.incluirEnIndice = incluirEnIndice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_tramites.fecha_modificacion
	 * @return  the value of modlic_tramites.fecha_modificacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_tramites.fecha_modificacion
	 * @param fechaModificacion  the value for modlic_tramites.fecha_modificacion
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column modlic_tramites.ip_cliente
	 * @return  the value of modlic_tramites.ip_cliente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getIpCliente() {
		return ipCliente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column modlic_tramites.ip_cliente
	 * @param ipCliente  the value for modlic_tramites.ip_cliente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setIpCliente(String ipCliente) {
		this.ipCliente = ipCliente;
	}
}