package es.aalvarez.modelica.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class TramiteExpedienteExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public TramiteExpedienteExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdtramiteIsNull() {
			addCriterion("idTramite is null");
			return (Criteria) this;
		}

		public Criteria andIdtramiteIsNotNull() {
			addCriterion("idTramite is not null");
			return (Criteria) this;
		}

		public Criteria andIdtramiteEqualTo(Integer value) {
			addCriterion("idTramite =", value, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteNotEqualTo(Integer value) {
			addCriterion("idTramite <>", value, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteGreaterThan(Integer value) {
			addCriterion("idTramite >", value, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteGreaterThanOrEqualTo(Integer value) {
			addCriterion("idTramite >=", value, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteLessThan(Integer value) {
			addCriterion("idTramite <", value, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteLessThanOrEqualTo(Integer value) {
			addCriterion("idTramite <=", value, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteIn(List<Integer> values) {
			addCriterion("idTramite in", values, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteNotIn(List<Integer> values) {
			addCriterion("idTramite not in", values, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteBetween(Integer value1, Integer value2) {
			addCriterion("idTramite between", value1, value2, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteNotBetween(Integer value1, Integer value2) {
			addCriterion("idTramite not between", value1, value2, "idtramite");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteIsNull() {
			addCriterion("cod_modlic_expediente is null");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteIsNotNull() {
			addCriterion("cod_modlic_expediente is not null");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteEqualTo(Integer value) {
			addCriterion("cod_modlic_expediente =", value,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteNotEqualTo(Integer value) {
			addCriterion("cod_modlic_expediente <>", value,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteGreaterThan(Integer value) {
			addCriterion("cod_modlic_expediente >", value,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteGreaterThanOrEqualTo(Integer value) {
			addCriterion("cod_modlic_expediente >=", value,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteLessThan(Integer value) {
			addCriterion("cod_modlic_expediente <", value,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteLessThanOrEqualTo(Integer value) {
			addCriterion("cod_modlic_expediente <=", value,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteIn(List<Integer> values) {
			addCriterion("cod_modlic_expediente in", values,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteNotIn(List<Integer> values) {
			addCriterion("cod_modlic_expediente not in", values,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteBetween(Integer value1,
				Integer value2) {
			addCriterion("cod_modlic_expediente between", value1, value2,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteNotBetween(Integer value1,
				Integer value2) {
			addCriterion("cod_modlic_expediente not between", value1, value2,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteIsNull() {
			addCriterion("fecha_tramite is null");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteIsNotNull() {
			addCriterion("fecha_tramite is not null");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteEqualTo(Date value) {
			addCriterion("fecha_tramite =", value, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteNotEqualTo(Date value) {
			addCriterion("fecha_tramite <>", value, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteGreaterThan(Date value) {
			addCriterion("fecha_tramite >", value, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteGreaterThanOrEqualTo(Date value) {
			addCriterion("fecha_tramite >=", value, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteLessThan(Date value) {
			addCriterion("fecha_tramite <", value, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteLessThanOrEqualTo(Date value) {
			addCriterion("fecha_tramite <=", value, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteIn(List<Date> values) {
			addCriterion("fecha_tramite in", values, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteNotIn(List<Date> values) {
			addCriterion("fecha_tramite not in", values, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteBetween(Date value1, Date value2) {
			addCriterion("fecha_tramite between", value1, value2,
					"fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteNotBetween(Date value1, Date value2) {
			addCriterion("fecha_tramite not between", value1, value2,
					"fechaTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteIsNull() {
			addCriterion("descripcion_tramite is null");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteIsNotNull() {
			addCriterion("descripcion_tramite is not null");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteEqualTo(String value) {
			addCriterion("descripcion_tramite =", value, "descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteNotEqualTo(String value) {
			addCriterion("descripcion_tramite <>", value, "descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteGreaterThan(String value) {
			addCriterion("descripcion_tramite >", value, "descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteGreaterThanOrEqualTo(String value) {
			addCriterion("descripcion_tramite >=", value, "descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteLessThan(String value) {
			addCriterion("descripcion_tramite <", value, "descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteLessThanOrEqualTo(String value) {
			addCriterion("descripcion_tramite <=", value, "descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteLike(String value) {
			addCriterion("descripcion_tramite like", value,
					"descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteNotLike(String value) {
			addCriterion("descripcion_tramite not like", value,
					"descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteIn(List<String> values) {
			addCriterion("descripcion_tramite in", values, "descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteNotIn(List<String> values) {
			addCriterion("descripcion_tramite not in", values,
					"descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteBetween(String value1,
				String value2) {
			addCriterion("descripcion_tramite between", value1, value2,
					"descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteNotBetween(String value1,
				String value2) {
			addCriterion("descripcion_tramite not between", value1, value2,
					"descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoAIsNull() {
			addCriterion("tramite_asignado_a is null");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoAIsNotNull() {
			addCriterion("tramite_asignado_a is not null");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoAEqualTo(String value) {
			addCriterion("tramite_asignado_a =", value, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoANotEqualTo(String value) {
			addCriterion("tramite_asignado_a <>", value, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoAGreaterThan(String value) {
			addCriterion("tramite_asignado_a >", value, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoAGreaterThanOrEqualTo(String value) {
			addCriterion("tramite_asignado_a >=", value, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoALessThan(String value) {
			addCriterion("tramite_asignado_a <", value, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoALessThanOrEqualTo(String value) {
			addCriterion("tramite_asignado_a <=", value, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoALike(String value) {
			addCriterion("tramite_asignado_a like", value, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoANotLike(String value) {
			addCriterion("tramite_asignado_a not like", value,
					"tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoAIn(List<String> values) {
			addCriterion("tramite_asignado_a in", values, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoANotIn(List<String> values) {
			addCriterion("tramite_asignado_a not in", values,
					"tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoABetween(String value1, String value2) {
			addCriterion("tramite_asignado_a between", value1, value2,
					"tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoANotBetween(String value1,
				String value2) {
			addCriterion("tramite_asignado_a not between", value1, value2,
					"tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoIsNull() {
			addCriterion("tramite_activo is null");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoIsNotNull() {
			addCriterion("tramite_activo is not null");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoEqualTo(Boolean value) {
			addCriterion("tramite_activo =", value, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoNotEqualTo(Boolean value) {
			addCriterion("tramite_activo <>", value, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoGreaterThan(Boolean value) {
			addCriterion("tramite_activo >", value, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("tramite_activo >=", value, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoLessThan(Boolean value) {
			addCriterion("tramite_activo <", value, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoLessThanOrEqualTo(Boolean value) {
			addCriterion("tramite_activo <=", value, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoIn(List<Boolean> values) {
			addCriterion("tramite_activo in", values, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoNotIn(List<Boolean> values) {
			addCriterion("tramite_activo not in", values, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoBetween(Boolean value1, Boolean value2) {
			addCriterion("tramite_activo between", value1, value2,
					"tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("tramite_activo not between", value1, value2,
					"tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteIsNull() {
			addCriterion("estado_tramite is null");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteIsNotNull() {
			addCriterion("estado_tramite is not null");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteEqualTo(String value) {
			addCriterion("estado_tramite =", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteNotEqualTo(String value) {
			addCriterion("estado_tramite <>", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteGreaterThan(String value) {
			addCriterion("estado_tramite >", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteGreaterThanOrEqualTo(String value) {
			addCriterion("estado_tramite >=", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteLessThan(String value) {
			addCriterion("estado_tramite <", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteLessThanOrEqualTo(String value) {
			addCriterion("estado_tramite <=", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteLike(String value) {
			addCriterion("estado_tramite like", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteNotLike(String value) {
			addCriterion("estado_tramite not like", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteIn(List<String> values) {
			addCriterion("estado_tramite in", values, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteNotIn(List<String> values) {
			addCriterion("estado_tramite not in", values, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteBetween(String value1, String value2) {
			addCriterion("estado_tramite between", value1, value2,
					"estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteNotBetween(String value1, String value2) {
			addCriterion("estado_tramite not between", value1, value2,
					"estadoTramite");
			return (Criteria) this;
		}

		public Criteria andIncluirEnIndiceIsNull() {
			addCriterion("incluir_en_indice is null");
			return (Criteria) this;
		}

		public Criteria andIncluirEnIndiceIsNotNull() {
			addCriterion("incluir_en_indice is not null");
			return (Criteria) this;
		}

		public Criteria andIncluirEnIndiceEqualTo(Boolean value) {
			addCriterion("incluir_en_indice =", value, "incluirEnIndice");
			return (Criteria) this;
		}

		public Criteria andIncluirEnIndiceNotEqualTo(Boolean value) {
			addCriterion("incluir_en_indice <>", value, "incluirEnIndice");
			return (Criteria) this;
		}

		public Criteria andIncluirEnIndiceGreaterThan(Boolean value) {
			addCriterion("incluir_en_indice >", value, "incluirEnIndice");
			return (Criteria) this;
		}

		public Criteria andIncluirEnIndiceGreaterThanOrEqualTo(Boolean value) {
			addCriterion("incluir_en_indice >=", value, "incluirEnIndice");
			return (Criteria) this;
		}

		public Criteria andIncluirEnIndiceLessThan(Boolean value) {
			addCriterion("incluir_en_indice <", value, "incluirEnIndice");
			return (Criteria) this;
		}

		public Criteria andIncluirEnIndiceLessThanOrEqualTo(Boolean value) {
			addCriterion("incluir_en_indice <=", value, "incluirEnIndice");
			return (Criteria) this;
		}

		public Criteria andIncluirEnIndiceIn(List<Boolean> values) {
			addCriterion("incluir_en_indice in", values, "incluirEnIndice");
			return (Criteria) this;
		}

		public Criteria andIncluirEnIndiceNotIn(List<Boolean> values) {
			addCriterion("incluir_en_indice not in", values, "incluirEnIndice");
			return (Criteria) this;
		}

		public Criteria andIncluirEnIndiceBetween(Boolean value1, Boolean value2) {
			addCriterion("incluir_en_indice between", value1, value2,
					"incluirEnIndice");
			return (Criteria) this;
		}

		public Criteria andIncluirEnIndiceNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("incluir_en_indice not between", value1, value2,
					"incluirEnIndice");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionIsNull() {
			addCriterion("fecha_modificacion is null");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionIsNotNull() {
			addCriterion("fecha_modificacion is not null");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionEqualTo(Date value) {
			addCriterion("fecha_modificacion =", value, "fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionNotEqualTo(Date value) {
			addCriterion("fecha_modificacion <>", value, "fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionGreaterThan(Date value) {
			addCriterion("fecha_modificacion >", value, "fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionGreaterThanOrEqualTo(Date value) {
			addCriterion("fecha_modificacion >=", value, "fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionLessThan(Date value) {
			addCriterion("fecha_modificacion <", value, "fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionLessThanOrEqualTo(Date value) {
			addCriterion("fecha_modificacion <=", value, "fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionIn(List<Date> values) {
			addCriterion("fecha_modificacion in", values, "fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionNotIn(List<Date> values) {
			addCriterion("fecha_modificacion not in", values,
					"fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionBetween(Date value1, Date value2) {
			addCriterion("fecha_modificacion between", value1, value2,
					"fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionNotBetween(Date value1, Date value2) {
			addCriterion("fecha_modificacion not between", value1, value2,
					"fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andIpClienteIsNull() {
			addCriterion("ip_cliente is null");
			return (Criteria) this;
		}

		public Criteria andIpClienteIsNotNull() {
			addCriterion("ip_cliente is not null");
			return (Criteria) this;
		}

		public Criteria andIpClienteEqualTo(String value) {
			addCriterion("ip_cliente =", value, "ipCliente");
			return (Criteria) this;
		}

		public Criteria andIpClienteNotEqualTo(String value) {
			addCriterion("ip_cliente <>", value, "ipCliente");
			return (Criteria) this;
		}

		public Criteria andIpClienteGreaterThan(String value) {
			addCriterion("ip_cliente >", value, "ipCliente");
			return (Criteria) this;
		}

		public Criteria andIpClienteGreaterThanOrEqualTo(String value) {
			addCriterion("ip_cliente >=", value, "ipCliente");
			return (Criteria) this;
		}

		public Criteria andIpClienteLessThan(String value) {
			addCriterion("ip_cliente <", value, "ipCliente");
			return (Criteria) this;
		}

		public Criteria andIpClienteLessThanOrEqualTo(String value) {
			addCriterion("ip_cliente <=", value, "ipCliente");
			return (Criteria) this;
		}

		public Criteria andIpClienteLike(String value) {
			addCriterion("ip_cliente like", value, "ipCliente");
			return (Criteria) this;
		}

		public Criteria andIpClienteNotLike(String value) {
			addCriterion("ip_cliente not like", value, "ipCliente");
			return (Criteria) this;
		}

		public Criteria andIpClienteIn(List<String> values) {
			addCriterion("ip_cliente in", values, "ipCliente");
			return (Criteria) this;
		}

		public Criteria andIpClienteNotIn(List<String> values) {
			addCriterion("ip_cliente not in", values, "ipCliente");
			return (Criteria) this;
		}

		public Criteria andIpClienteBetween(String value1, String value2) {
			addCriterion("ip_cliente between", value1, value2, "ipCliente");
			return (Criteria) this;
		}

		public Criteria andIpClienteNotBetween(String value1, String value2) {
			addCriterion("ip_cliente not between", value1, value2, "ipCliente");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table modlic_tramites
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table modlic_tramites
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 25 10:26:06 CET 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}