package es.aalvarez.modelica.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TramiteActivoXExpedienteExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public TramiteActivoXExpedienteExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNumEntradaIsNull() {
			addCriterion("num_entrada is null");
			return (Criteria) this;
		}

		public Criteria andNumEntradaIsNotNull() {
			addCriterion("num_entrada is not null");
			return (Criteria) this;
		}

		public Criteria andNumEntradaEqualTo(Integer value) {
			addCriterion("num_entrada =", value, "numEntrada");
			return (Criteria) this;
		}

		public Criteria andNumEntradaNotEqualTo(Integer value) {
			addCriterion("num_entrada <>", value, "numEntrada");
			return (Criteria) this;
		}

		public Criteria andNumEntradaGreaterThan(Integer value) {
			addCriterion("num_entrada >", value, "numEntrada");
			return (Criteria) this;
		}

		public Criteria andNumEntradaGreaterThanOrEqualTo(Integer value) {
			addCriterion("num_entrada >=", value, "numEntrada");
			return (Criteria) this;
		}

		public Criteria andNumEntradaLessThan(Integer value) {
			addCriterion("num_entrada <", value, "numEntrada");
			return (Criteria) this;
		}

		public Criteria andNumEntradaLessThanOrEqualTo(Integer value) {
			addCriterion("num_entrada <=", value, "numEntrada");
			return (Criteria) this;
		}

		public Criteria andNumEntradaIn(List<Integer> values) {
			addCriterion("num_entrada in", values, "numEntrada");
			return (Criteria) this;
		}

		public Criteria andNumEntradaNotIn(List<Integer> values) {
			addCriterion("num_entrada not in", values, "numEntrada");
			return (Criteria) this;
		}

		public Criteria andNumEntradaBetween(Integer value1, Integer value2) {
			addCriterion("num_entrada between", value1, value2, "numEntrada");
			return (Criteria) this;
		}

		public Criteria andNumEntradaNotBetween(Integer value1, Integer value2) {
			addCriterion("num_entrada not between", value1, value2,
					"numEntrada");
			return (Criteria) this;
		}

		public Criteria andFechaEntradaIsNull() {
			addCriterion("fecha_entrada is null");
			return (Criteria) this;
		}

		public Criteria andFechaEntradaIsNotNull() {
			addCriterion("fecha_entrada is not null");
			return (Criteria) this;
		}

		public Criteria andFechaEntradaEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_entrada =", value, "fechaEntrada");
			return (Criteria) this;
		}

		public Criteria andFechaEntradaNotEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_entrada <>", value, "fechaEntrada");
			return (Criteria) this;
		}

		public Criteria andFechaEntradaGreaterThan(Date value) {
			addCriterionForJDBCDate("fecha_entrada >", value, "fechaEntrada");
			return (Criteria) this;
		}

		public Criteria andFechaEntradaGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_entrada >=", value, "fechaEntrada");
			return (Criteria) this;
		}

		public Criteria andFechaEntradaLessThan(Date value) {
			addCriterionForJDBCDate("fecha_entrada <", value, "fechaEntrada");
			return (Criteria) this;
		}

		public Criteria andFechaEntradaLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_entrada <=", value, "fechaEntrada");
			return (Criteria) this;
		}

		public Criteria andFechaEntradaIn(List<Date> values) {
			addCriterionForJDBCDate("fecha_entrada in", values, "fechaEntrada");
			return (Criteria) this;
		}

		public Criteria andFechaEntradaNotIn(List<Date> values) {
			addCriterionForJDBCDate("fecha_entrada not in", values,
					"fechaEntrada");
			return (Criteria) this;
		}

		public Criteria andFechaEntradaBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("fecha_entrada between", value1, value2,
					"fechaEntrada");
			return (Criteria) this;
		}

		public Criteria andFechaEntradaNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("fecha_entrada not between", value1,
					value2, "fechaEntrada");
			return (Criteria) this;
		}

		public Criteria andTipoExpedienteIsNull() {
			addCriterion("tipo_expediente is null");
			return (Criteria) this;
		}

		public Criteria andTipoExpedienteIsNotNull() {
			addCriterion("tipo_expediente is not null");
			return (Criteria) this;
		}

		public Criteria andTipoExpedienteEqualTo(String value) {
			addCriterion("tipo_expediente =", value, "tipoExpediente");
			return (Criteria) this;
		}

		public Criteria andTipoExpedienteNotEqualTo(String value) {
			addCriterion("tipo_expediente <>", value, "tipoExpediente");
			return (Criteria) this;
		}

		public Criteria andTipoExpedienteGreaterThan(String value) {
			addCriterion("tipo_expediente >", value, "tipoExpediente");
			return (Criteria) this;
		}

		public Criteria andTipoExpedienteGreaterThanOrEqualTo(String value) {
			addCriterion("tipo_expediente >=", value, "tipoExpediente");
			return (Criteria) this;
		}

		public Criteria andTipoExpedienteLessThan(String value) {
			addCriterion("tipo_expediente <", value, "tipoExpediente");
			return (Criteria) this;
		}

		public Criteria andTipoExpedienteLessThanOrEqualTo(String value) {
			addCriterion("tipo_expediente <=", value, "tipoExpediente");
			return (Criteria) this;
		}

		public Criteria andTipoExpedienteLike(String value) {
			addCriterion("tipo_expediente like", value, "tipoExpediente");
			return (Criteria) this;
		}

		public Criteria andTipoExpedienteNotLike(String value) {
			addCriterion("tipo_expediente not like", value, "tipoExpediente");
			return (Criteria) this;
		}

		public Criteria andTipoExpedienteIn(List<String> values) {
			addCriterion("tipo_expediente in", values, "tipoExpediente");
			return (Criteria) this;
		}

		public Criteria andTipoExpedienteNotIn(List<String> values) {
			addCriterion("tipo_expediente not in", values, "tipoExpediente");
			return (Criteria) this;
		}

		public Criteria andTipoExpedienteBetween(String value1, String value2) {
			addCriterion("tipo_expediente between", value1, value2,
					"tipoExpediente");
			return (Criteria) this;
		}

		public Criteria andTipoExpedienteNotBetween(String value1, String value2) {
			addCriterion("tipo_expediente not between", value1, value2,
					"tipoExpediente");
			return (Criteria) this;
		}

		public Criteria andExpedienteIsNull() {
			addCriterion("expediente is null");
			return (Criteria) this;
		}

		public Criteria andExpedienteIsNotNull() {
			addCriterion("expediente is not null");
			return (Criteria) this;
		}

		public Criteria andExpedienteEqualTo(Integer value) {
			addCriterion("expediente =", value, "expediente");
			return (Criteria) this;
		}

		public Criteria andExpedienteNotEqualTo(Integer value) {
			addCriterion("expediente <>", value, "expediente");
			return (Criteria) this;
		}

		public Criteria andExpedienteGreaterThan(Integer value) {
			addCriterion("expediente >", value, "expediente");
			return (Criteria) this;
		}

		public Criteria andExpedienteGreaterThanOrEqualTo(Integer value) {
			addCriterion("expediente >=", value, "expediente");
			return (Criteria) this;
		}

		public Criteria andExpedienteLessThan(Integer value) {
			addCriterion("expediente <", value, "expediente");
			return (Criteria) this;
		}

		public Criteria andExpedienteLessThanOrEqualTo(Integer value) {
			addCriterion("expediente <=", value, "expediente");
			return (Criteria) this;
		}

		public Criteria andExpedienteIn(List<Integer> values) {
			addCriterion("expediente in", values, "expediente");
			return (Criteria) this;
		}

		public Criteria andExpedienteNotIn(List<Integer> values) {
			addCriterion("expediente not in", values, "expediente");
			return (Criteria) this;
		}

		public Criteria andExpedienteBetween(Integer value1, Integer value2) {
			addCriterion("expediente between", value1, value2, "expediente");
			return (Criteria) this;
		}

		public Criteria andExpedienteNotBetween(Integer value1, Integer value2) {
			addCriterion("expediente not between", value1, value2, "expediente");
			return (Criteria) this;
		}

		public Criteria andAnyoIsNull() {
			addCriterion("anyo is null");
			return (Criteria) this;
		}

		public Criteria andAnyoIsNotNull() {
			addCriterion("anyo is not null");
			return (Criteria) this;
		}

		public Criteria andAnyoEqualTo(Integer value) {
			addCriterion("anyo =", value, "anyo");
			return (Criteria) this;
		}

		public Criteria andAnyoNotEqualTo(Integer value) {
			addCriterion("anyo <>", value, "anyo");
			return (Criteria) this;
		}

		public Criteria andAnyoGreaterThan(Integer value) {
			addCriterion("anyo >", value, "anyo");
			return (Criteria) this;
		}

		public Criteria andAnyoGreaterThanOrEqualTo(Integer value) {
			addCriterion("anyo >=", value, "anyo");
			return (Criteria) this;
		}

		public Criteria andAnyoLessThan(Integer value) {
			addCriterion("anyo <", value, "anyo");
			return (Criteria) this;
		}

		public Criteria andAnyoLessThanOrEqualTo(Integer value) {
			addCriterion("anyo <=", value, "anyo");
			return (Criteria) this;
		}

		public Criteria andAnyoIn(List<Integer> values) {
			addCriterion("anyo in", values, "anyo");
			return (Criteria) this;
		}

		public Criteria andAnyoNotIn(List<Integer> values) {
			addCriterion("anyo not in", values, "anyo");
			return (Criteria) this;
		}

		public Criteria andAnyoBetween(Integer value1, Integer value2) {
			addCriterion("anyo between", value1, value2, "anyo");
			return (Criteria) this;
		}

		public Criteria andAnyoNotBetween(Integer value1, Integer value2) {
			addCriterion("anyo not between", value1, value2, "anyo");
			return (Criteria) this;
		}

		public Criteria andInteresadoIsNull() {
			addCriterion("interesado is null");
			return (Criteria) this;
		}

		public Criteria andInteresadoIsNotNull() {
			addCriterion("interesado is not null");
			return (Criteria) this;
		}

		public Criteria andInteresadoEqualTo(String value) {
			addCriterion("interesado =", value, "interesado");
			return (Criteria) this;
		}

		public Criteria andInteresadoNotEqualTo(String value) {
			addCriterion("interesado <>", value, "interesado");
			return (Criteria) this;
		}

		public Criteria andInteresadoGreaterThan(String value) {
			addCriterion("interesado >", value, "interesado");
			return (Criteria) this;
		}

		public Criteria andInteresadoGreaterThanOrEqualTo(String value) {
			addCriterion("interesado >=", value, "interesado");
			return (Criteria) this;
		}

		public Criteria andInteresadoLessThan(String value) {
			addCriterion("interesado <", value, "interesado");
			return (Criteria) this;
		}

		public Criteria andInteresadoLessThanOrEqualTo(String value) {
			addCriterion("interesado <=", value, "interesado");
			return (Criteria) this;
		}

		public Criteria andInteresadoLike(String value) {
			addCriterion("interesado like", value, "interesado");
			return (Criteria) this;
		}

		public Criteria andInteresadoNotLike(String value) {
			addCriterion("interesado not like", value, "interesado");
			return (Criteria) this;
		}

		public Criteria andInteresadoIn(List<String> values) {
			addCriterion("interesado in", values, "interesado");
			return (Criteria) this;
		}

		public Criteria andInteresadoNotIn(List<String> values) {
			addCriterion("interesado not in", values, "interesado");
			return (Criteria) this;
		}

		public Criteria andInteresadoBetween(String value1, String value2) {
			addCriterion("interesado between", value1, value2, "interesado");
			return (Criteria) this;
		}

		public Criteria andInteresadoNotBetween(String value1, String value2) {
			addCriterion("interesado not between", value1, value2, "interesado");
			return (Criteria) this;
		}

		public Criteria andNifInteresadoIsNull() {
			addCriterion("nif_interesado is null");
			return (Criteria) this;
		}

		public Criteria andNifInteresadoIsNotNull() {
			addCriterion("nif_interesado is not null");
			return (Criteria) this;
		}

		public Criteria andNifInteresadoEqualTo(String value) {
			addCriterion("nif_interesado =", value, "nifInteresado");
			return (Criteria) this;
		}

		public Criteria andNifInteresadoNotEqualTo(String value) {
			addCriterion("nif_interesado <>", value, "nifInteresado");
			return (Criteria) this;
		}

		public Criteria andNifInteresadoGreaterThan(String value) {
			addCriterion("nif_interesado >", value, "nifInteresado");
			return (Criteria) this;
		}

		public Criteria andNifInteresadoGreaterThanOrEqualTo(String value) {
			addCriterion("nif_interesado >=", value, "nifInteresado");
			return (Criteria) this;
		}

		public Criteria andNifInteresadoLessThan(String value) {
			addCriterion("nif_interesado <", value, "nifInteresado");
			return (Criteria) this;
		}

		public Criteria andNifInteresadoLessThanOrEqualTo(String value) {
			addCriterion("nif_interesado <=", value, "nifInteresado");
			return (Criteria) this;
		}

		public Criteria andNifInteresadoLike(String value) {
			addCriterion("nif_interesado like", value, "nifInteresado");
			return (Criteria) this;
		}

		public Criteria andNifInteresadoNotLike(String value) {
			addCriterion("nif_interesado not like", value, "nifInteresado");
			return (Criteria) this;
		}

		public Criteria andNifInteresadoIn(List<String> values) {
			addCriterion("nif_interesado in", values, "nifInteresado");
			return (Criteria) this;
		}

		public Criteria andNifInteresadoNotIn(List<String> values) {
			addCriterion("nif_interesado not in", values, "nifInteresado");
			return (Criteria) this;
		}

		public Criteria andNifInteresadoBetween(String value1, String value2) {
			addCriterion("nif_interesado between", value1, value2,
					"nifInteresado");
			return (Criteria) this;
		}

		public Criteria andNifInteresadoNotBetween(String value1, String value2) {
			addCriterion("nif_interesado not between", value1, value2,
					"nifInteresado");
			return (Criteria) this;
		}

		public Criteria andEstadoExpedienteIsNull() {
			addCriterion("estado_expediente is null");
			return (Criteria) this;
		}

		public Criteria andEstadoExpedienteIsNotNull() {
			addCriterion("estado_expediente is not null");
			return (Criteria) this;
		}

		public Criteria andEstadoExpedienteEqualTo(String value) {
			addCriterion("estado_expediente =", value, "estadoExpediente");
			return (Criteria) this;
		}

		public Criteria andEstadoExpedienteNotEqualTo(String value) {
			addCriterion("estado_expediente <>", value, "estadoExpediente");
			return (Criteria) this;
		}

		public Criteria andEstadoExpedienteGreaterThan(String value) {
			addCriterion("estado_expediente >", value, "estadoExpediente");
			return (Criteria) this;
		}

		public Criteria andEstadoExpedienteGreaterThanOrEqualTo(String value) {
			addCriterion("estado_expediente >=", value, "estadoExpediente");
			return (Criteria) this;
		}

		public Criteria andEstadoExpedienteLessThan(String value) {
			addCriterion("estado_expediente <", value, "estadoExpediente");
			return (Criteria) this;
		}

		public Criteria andEstadoExpedienteLessThanOrEqualTo(String value) {
			addCriterion("estado_expediente <=", value, "estadoExpediente");
			return (Criteria) this;
		}

		public Criteria andEstadoExpedienteLike(String value) {
			addCriterion("estado_expediente like", value, "estadoExpediente");
			return (Criteria) this;
		}

		public Criteria andEstadoExpedienteNotLike(String value) {
			addCriterion("estado_expediente not like", value,
					"estadoExpediente");
			return (Criteria) this;
		}

		public Criteria andEstadoExpedienteIn(List<String> values) {
			addCriterion("estado_expediente in", values, "estadoExpediente");
			return (Criteria) this;
		}

		public Criteria andEstadoExpedienteNotIn(List<String> values) {
			addCriterion("estado_expediente not in", values, "estadoExpediente");
			return (Criteria) this;
		}

		public Criteria andEstadoExpedienteBetween(String value1, String value2) {
			addCriterion("estado_expediente between", value1, value2,
					"estadoExpediente");
			return (Criteria) this;
		}

		public Criteria andEstadoExpedienteNotBetween(String value1,
				String value2) {
			addCriterion("estado_expediente not between", value1, value2,
					"estadoExpediente");
			return (Criteria) this;
		}

		public Criteria andFaseExpedienteIsNull() {
			addCriterion("fase_expediente is null");
			return (Criteria) this;
		}

		public Criteria andFaseExpedienteIsNotNull() {
			addCriterion("fase_expediente is not null");
			return (Criteria) this;
		}

		public Criteria andFaseExpedienteEqualTo(Integer value) {
			addCriterion("fase_expediente =", value, "faseExpediente");
			return (Criteria) this;
		}

		public Criteria andFaseExpedienteNotEqualTo(Integer value) {
			addCriterion("fase_expediente <>", value, "faseExpediente");
			return (Criteria) this;
		}

		public Criteria andFaseExpedienteGreaterThan(Integer value) {
			addCriterion("fase_expediente >", value, "faseExpediente");
			return (Criteria) this;
		}

		public Criteria andFaseExpedienteGreaterThanOrEqualTo(Integer value) {
			addCriterion("fase_expediente >=", value, "faseExpediente");
			return (Criteria) this;
		}

		public Criteria andFaseExpedienteLessThan(Integer value) {
			addCriterion("fase_expediente <", value, "faseExpediente");
			return (Criteria) this;
		}

		public Criteria andFaseExpedienteLessThanOrEqualTo(Integer value) {
			addCriterion("fase_expediente <=", value, "faseExpediente");
			return (Criteria) this;
		}

		public Criteria andFaseExpedienteIn(List<Integer> values) {
			addCriterion("fase_expediente in", values, "faseExpediente");
			return (Criteria) this;
		}

		public Criteria andFaseExpedienteNotIn(List<Integer> values) {
			addCriterion("fase_expediente not in", values, "faseExpediente");
			return (Criteria) this;
		}

		public Criteria andFaseExpedienteBetween(Integer value1, Integer value2) {
			addCriterion("fase_expediente between", value1, value2,
					"faseExpediente");
			return (Criteria) this;
		}

		public Criteria andFaseExpedienteNotBetween(Integer value1,
				Integer value2) {
			addCriterion("fase_expediente not between", value1, value2,
					"faseExpediente");
			return (Criteria) this;
		}

		public Criteria andActuacionIsNull() {
			addCriterion("actuacion is null");
			return (Criteria) this;
		}

		public Criteria andActuacionIsNotNull() {
			addCriterion("actuacion is not null");
			return (Criteria) this;
		}

		public Criteria andActuacionEqualTo(String value) {
			addCriterion("actuacion =", value, "actuacion");
			return (Criteria) this;
		}

		public Criteria andActuacionNotEqualTo(String value) {
			addCriterion("actuacion <>", value, "actuacion");
			return (Criteria) this;
		}

		public Criteria andActuacionGreaterThan(String value) {
			addCriterion("actuacion >", value, "actuacion");
			return (Criteria) this;
		}

		public Criteria andActuacionGreaterThanOrEqualTo(String value) {
			addCriterion("actuacion >=", value, "actuacion");
			return (Criteria) this;
		}

		public Criteria andActuacionLessThan(String value) {
			addCriterion("actuacion <", value, "actuacion");
			return (Criteria) this;
		}

		public Criteria andActuacionLessThanOrEqualTo(String value) {
			addCriterion("actuacion <=", value, "actuacion");
			return (Criteria) this;
		}

		public Criteria andActuacionLike(String value) {
			addCriterion("actuacion like", value, "actuacion");
			return (Criteria) this;
		}

		public Criteria andActuacionNotLike(String value) {
			addCriterion("actuacion not like", value, "actuacion");
			return (Criteria) this;
		}

		public Criteria andActuacionIn(List<String> values) {
			addCriterion("actuacion in", values, "actuacion");
			return (Criteria) this;
		}

		public Criteria andActuacionNotIn(List<String> values) {
			addCriterion("actuacion not in", values, "actuacion");
			return (Criteria) this;
		}

		public Criteria andActuacionBetween(String value1, String value2) {
			addCriterion("actuacion between", value1, value2, "actuacion");
			return (Criteria) this;
		}

		public Criteria andActuacionNotBetween(String value1, String value2) {
			addCriterion("actuacion not between", value1, value2, "actuacion");
			return (Criteria) this;
		}

		public Criteria andEmplazamientoIsNull() {
			addCriterion("emplazamiento is null");
			return (Criteria) this;
		}

		public Criteria andEmplazamientoIsNotNull() {
			addCriterion("emplazamiento is not null");
			return (Criteria) this;
		}

		public Criteria andEmplazamientoEqualTo(String value) {
			addCriterion("emplazamiento =", value, "emplazamiento");
			return (Criteria) this;
		}

		public Criteria andEmplazamientoNotEqualTo(String value) {
			addCriterion("emplazamiento <>", value, "emplazamiento");
			return (Criteria) this;
		}

		public Criteria andEmplazamientoGreaterThan(String value) {
			addCriterion("emplazamiento >", value, "emplazamiento");
			return (Criteria) this;
		}

		public Criteria andEmplazamientoGreaterThanOrEqualTo(String value) {
			addCriterion("emplazamiento >=", value, "emplazamiento");
			return (Criteria) this;
		}

		public Criteria andEmplazamientoLessThan(String value) {
			addCriterion("emplazamiento <", value, "emplazamiento");
			return (Criteria) this;
		}

		public Criteria andEmplazamientoLessThanOrEqualTo(String value) {
			addCriterion("emplazamiento <=", value, "emplazamiento");
			return (Criteria) this;
		}

		public Criteria andEmplazamientoLike(String value) {
			addCriterion("emplazamiento like", value, "emplazamiento");
			return (Criteria) this;
		}

		public Criteria andEmplazamientoNotLike(String value) {
			addCriterion("emplazamiento not like", value, "emplazamiento");
			return (Criteria) this;
		}

		public Criteria andEmplazamientoIn(List<String> values) {
			addCriterion("emplazamiento in", values, "emplazamiento");
			return (Criteria) this;
		}

		public Criteria andEmplazamientoNotIn(List<String> values) {
			addCriterion("emplazamiento not in", values, "emplazamiento");
			return (Criteria) this;
		}

		public Criteria andEmplazamientoBetween(String value1, String value2) {
			addCriterion("emplazamiento between", value1, value2,
					"emplazamiento");
			return (Criteria) this;
		}

		public Criteria andEmplazamientoNotBetween(String value1, String value2) {
			addCriterion("emplazamiento not between", value1, value2,
					"emplazamiento");
			return (Criteria) this;
		}

		public Criteria andRefCatastralIsNull() {
			addCriterion("ref_catastral is null");
			return (Criteria) this;
		}

		public Criteria andRefCatastralIsNotNull() {
			addCriterion("ref_catastral is not null");
			return (Criteria) this;
		}

		public Criteria andRefCatastralEqualTo(String value) {
			addCriterion("ref_catastral =", value, "refCatastral");
			return (Criteria) this;
		}

		public Criteria andRefCatastralNotEqualTo(String value) {
			addCriterion("ref_catastral <>", value, "refCatastral");
			return (Criteria) this;
		}

		public Criteria andRefCatastralGreaterThan(String value) {
			addCriterion("ref_catastral >", value, "refCatastral");
			return (Criteria) this;
		}

		public Criteria andRefCatastralGreaterThanOrEqualTo(String value) {
			addCriterion("ref_catastral >=", value, "refCatastral");
			return (Criteria) this;
		}

		public Criteria andRefCatastralLessThan(String value) {
			addCriterion("ref_catastral <", value, "refCatastral");
			return (Criteria) this;
		}

		public Criteria andRefCatastralLessThanOrEqualTo(String value) {
			addCriterion("ref_catastral <=", value, "refCatastral");
			return (Criteria) this;
		}

		public Criteria andRefCatastralLike(String value) {
			addCriterion("ref_catastral like", value, "refCatastral");
			return (Criteria) this;
		}

		public Criteria andRefCatastralNotLike(String value) {
			addCriterion("ref_catastral not like", value, "refCatastral");
			return (Criteria) this;
		}

		public Criteria andRefCatastralIn(List<String> values) {
			addCriterion("ref_catastral in", values, "refCatastral");
			return (Criteria) this;
		}

		public Criteria andRefCatastralNotIn(List<String> values) {
			addCriterion("ref_catastral not in", values, "refCatastral");
			return (Criteria) this;
		}

		public Criteria andRefCatastralBetween(String value1, String value2) {
			addCriterion("ref_catastral between", value1, value2,
					"refCatastral");
			return (Criteria) this;
		}

		public Criteria andRefCatastralNotBetween(String value1, String value2) {
			addCriterion("ref_catastral not between", value1, value2,
					"refCatastral");
			return (Criteria) this;
		}

		public Criteria andExpedienteFinalizadoIsNull() {
			addCriterion("expediente_finalizado is null");
			return (Criteria) this;
		}

		public Criteria andExpedienteFinalizadoIsNotNull() {
			addCriterion("expediente_finalizado is not null");
			return (Criteria) this;
		}

		public Criteria andExpedienteFinalizadoEqualTo(Boolean value) {
			addCriterion("expediente_finalizado =", value,
					"expedienteFinalizado");
			return (Criteria) this;
		}

		public Criteria andExpedienteFinalizadoNotEqualTo(Boolean value) {
			addCriterion("expediente_finalizado <>", value,
					"expedienteFinalizado");
			return (Criteria) this;
		}

		public Criteria andExpedienteFinalizadoGreaterThan(Boolean value) {
			addCriterion("expediente_finalizado >", value,
					"expedienteFinalizado");
			return (Criteria) this;
		}

		public Criteria andExpedienteFinalizadoGreaterThanOrEqualTo(
				Boolean value) {
			addCriterion("expediente_finalizado >=", value,
					"expedienteFinalizado");
			return (Criteria) this;
		}

		public Criteria andExpedienteFinalizadoLessThan(Boolean value) {
			addCriterion("expediente_finalizado <", value,
					"expedienteFinalizado");
			return (Criteria) this;
		}

		public Criteria andExpedienteFinalizadoLessThanOrEqualTo(Boolean value) {
			addCriterion("expediente_finalizado <=", value,
					"expedienteFinalizado");
			return (Criteria) this;
		}

		public Criteria andExpedienteFinalizadoIn(List<Boolean> values) {
			addCriterion("expediente_finalizado in", values,
					"expedienteFinalizado");
			return (Criteria) this;
		}

		public Criteria andExpedienteFinalizadoNotIn(List<Boolean> values) {
			addCriterion("expediente_finalizado not in", values,
					"expedienteFinalizado");
			return (Criteria) this;
		}

		public Criteria andExpedienteFinalizadoBetween(Boolean value1,
				Boolean value2) {
			addCriterion("expediente_finalizado between", value1, value2,
					"expedienteFinalizado");
			return (Criteria) this;
		}

		public Criteria andExpedienteFinalizadoNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("expediente_finalizado not between", value1, value2,
					"expedienteFinalizado");
			return (Criteria) this;
		}

		public Criteria andIdtramiteIsNull() {
			addCriterion("idTramite is null");
			return (Criteria) this;
		}

		public Criteria andIdtramiteIsNotNull() {
			addCriterion("idTramite is not null");
			return (Criteria) this;
		}

		public Criteria andIdtramiteEqualTo(Integer value) {
			addCriterion("idTramite =", value, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteNotEqualTo(Integer value) {
			addCriterion("idTramite <>", value, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteGreaterThan(Integer value) {
			addCriterion("idTramite >", value, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteGreaterThanOrEqualTo(Integer value) {
			addCriterion("idTramite >=", value, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteLessThan(Integer value) {
			addCriterion("idTramite <", value, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteLessThanOrEqualTo(Integer value) {
			addCriterion("idTramite <=", value, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteIn(List<Integer> values) {
			addCriterion("idTramite in", values, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteNotIn(List<Integer> values) {
			addCriterion("idTramite not in", values, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteBetween(Integer value1, Integer value2) {
			addCriterion("idTramite between", value1, value2, "idtramite");
			return (Criteria) this;
		}

		public Criteria andIdtramiteNotBetween(Integer value1, Integer value2) {
			addCriterion("idTramite not between", value1, value2, "idtramite");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteIsNull() {
			addCriterion("cod_modlic_expediente is null");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteIsNotNull() {
			addCriterion("cod_modlic_expediente is not null");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteEqualTo(Integer value) {
			addCriterion("cod_modlic_expediente =", value,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteNotEqualTo(Integer value) {
			addCriterion("cod_modlic_expediente <>", value,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteGreaterThan(Integer value) {
			addCriterion("cod_modlic_expediente >", value,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteGreaterThanOrEqualTo(Integer value) {
			addCriterion("cod_modlic_expediente >=", value,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteLessThan(Integer value) {
			addCriterion("cod_modlic_expediente <", value,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteLessThanOrEqualTo(Integer value) {
			addCriterion("cod_modlic_expediente <=", value,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteIn(List<Integer> values) {
			addCriterion("cod_modlic_expediente in", values,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteNotIn(List<Integer> values) {
			addCriterion("cod_modlic_expediente not in", values,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteBetween(Integer value1,
				Integer value2) {
			addCriterion("cod_modlic_expediente between", value1, value2,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andCodModlicExpedienteNotBetween(Integer value1,
				Integer value2) {
			addCriterion("cod_modlic_expediente not between", value1, value2,
					"codModlicExpediente");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteIsNull() {
			addCriterion("fecha_tramite is null");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteIsNotNull() {
			addCriterion("fecha_tramite is not null");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteEqualTo(Date value) {
			addCriterion("fecha_tramite =", value, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteNotEqualTo(Date value) {
			addCriterion("fecha_tramite <>", value, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteGreaterThan(Date value) {
			addCriterion("fecha_tramite >", value, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteGreaterThanOrEqualTo(Date value) {
			addCriterion("fecha_tramite >=", value, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteLessThan(Date value) {
			addCriterion("fecha_tramite <", value, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteLessThanOrEqualTo(Date value) {
			addCriterion("fecha_tramite <=", value, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteIn(List<Date> values) {
			addCriterion("fecha_tramite in", values, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteNotIn(List<Date> values) {
			addCriterion("fecha_tramite not in", values, "fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteBetween(Date value1, Date value2) {
			addCriterion("fecha_tramite between", value1, value2,
					"fechaTramite");
			return (Criteria) this;
		}

		public Criteria andFechaTramiteNotBetween(Date value1, Date value2) {
			addCriterion("fecha_tramite not between", value1, value2,
					"fechaTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteIsNull() {
			addCriterion("descripcion_tramite is null");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteIsNotNull() {
			addCriterion("descripcion_tramite is not null");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteEqualTo(String value) {
			addCriterion("descripcion_tramite =", value, "descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteNotEqualTo(String value) {
			addCriterion("descripcion_tramite <>", value, "descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteGreaterThan(String value) {
			addCriterion("descripcion_tramite >", value, "descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteGreaterThanOrEqualTo(String value) {
			addCriterion("descripcion_tramite >=", value, "descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteLessThan(String value) {
			addCriterion("descripcion_tramite <", value, "descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteLessThanOrEqualTo(String value) {
			addCriterion("descripcion_tramite <=", value, "descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteLike(String value) {
			addCriterion("descripcion_tramite like", value,
					"descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteNotLike(String value) {
			addCriterion("descripcion_tramite not like", value,
					"descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteIn(List<String> values) {
			addCriterion("descripcion_tramite in", values, "descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteNotIn(List<String> values) {
			addCriterion("descripcion_tramite not in", values,
					"descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteBetween(String value1,
				String value2) {
			addCriterion("descripcion_tramite between", value1, value2,
					"descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andDescripcionTramiteNotBetween(String value1,
				String value2) {
			addCriterion("descripcion_tramite not between", value1, value2,
					"descripcionTramite");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoAIsNull() {
			addCriterion("tramite_asignado_a is null");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoAIsNotNull() {
			addCriterion("tramite_asignado_a is not null");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoAEqualTo(String value) {
			addCriterion("tramite_asignado_a =", value, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoANotEqualTo(String value) {
			addCriterion("tramite_asignado_a <>", value, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoAGreaterThan(String value) {
			addCriterion("tramite_asignado_a >", value, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoAGreaterThanOrEqualTo(String value) {
			addCriterion("tramite_asignado_a >=", value, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoALessThan(String value) {
			addCriterion("tramite_asignado_a <", value, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoALessThanOrEqualTo(String value) {
			addCriterion("tramite_asignado_a <=", value, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoALike(String value) {
			addCriterion("tramite_asignado_a like", value, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoANotLike(String value) {
			addCriterion("tramite_asignado_a not like", value,
					"tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoAIn(List<String> values) {
			addCriterion("tramite_asignado_a in", values, "tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoANotIn(List<String> values) {
			addCriterion("tramite_asignado_a not in", values,
					"tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoABetween(String value1, String value2) {
			addCriterion("tramite_asignado_a between", value1, value2,
					"tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteAsignadoANotBetween(String value1,
				String value2) {
			addCriterion("tramite_asignado_a not between", value1, value2,
					"tramiteAsignadoA");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoIsNull() {
			addCriterion("tramite_activo is null");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoIsNotNull() {
			addCriterion("tramite_activo is not null");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoEqualTo(Boolean value) {
			addCriterion("tramite_activo =", value, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoNotEqualTo(Boolean value) {
			addCriterion("tramite_activo <>", value, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoGreaterThan(Boolean value) {
			addCriterion("tramite_activo >", value, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("tramite_activo >=", value, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoLessThan(Boolean value) {
			addCriterion("tramite_activo <", value, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoLessThanOrEqualTo(Boolean value) {
			addCriterion("tramite_activo <=", value, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoIn(List<Boolean> values) {
			addCriterion("tramite_activo in", values, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoNotIn(List<Boolean> values) {
			addCriterion("tramite_activo not in", values, "tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoBetween(Boolean value1, Boolean value2) {
			addCriterion("tramite_activo between", value1, value2,
					"tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andTramiteActivoNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("tramite_activo not between", value1, value2,
					"tramiteActivo");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteIsNull() {
			addCriterion("estado_tramite is null");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteIsNotNull() {
			addCriterion("estado_tramite is not null");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteEqualTo(String value) {
			addCriterion("estado_tramite =", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteNotEqualTo(String value) {
			addCriterion("estado_tramite <>", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteGreaterThan(String value) {
			addCriterion("estado_tramite >", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteGreaterThanOrEqualTo(String value) {
			addCriterion("estado_tramite >=", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteLessThan(String value) {
			addCriterion("estado_tramite <", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteLessThanOrEqualTo(String value) {
			addCriterion("estado_tramite <=", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteLike(String value) {
			addCriterion("estado_tramite like", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteNotLike(String value) {
			addCriterion("estado_tramite not like", value, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteIn(List<String> values) {
			addCriterion("estado_tramite in", values, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteNotIn(List<String> values) {
			addCriterion("estado_tramite not in", values, "estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteBetween(String value1, String value2) {
			addCriterion("estado_tramite between", value1, value2,
					"estadoTramite");
			return (Criteria) this;
		}

		public Criteria andEstadoTramiteNotBetween(String value1, String value2) {
			addCriterion("estado_tramite not between", value1, value2,
					"estadoTramite");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table modlic_traxexpedienteview
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 05 21:28:51 CET 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}