package es.aalvarez.modelica.service;

import es.aalvarez.modelica.model.ArticuloInformeJuridico;
import es.aalvarez.modelica.model.ArticuloInformeJuridicoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticuloInformeJuridicoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int countByExample(ArticuloInformeJuridicoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int deleteByExample(ArticuloInformeJuridicoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int insert(ArticuloInformeJuridico record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int insertSelective(ArticuloInformeJuridico record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	List<ArticuloInformeJuridico> selectByExampleWithBLOBs(
			ArticuloInformeJuridicoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	List<ArticuloInformeJuridico> selectByExample(
			ArticuloInformeJuridicoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	ArticuloInformeJuridico selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByExampleSelective(
			@Param("record") ArticuloInformeJuridico record,
			@Param("example") ArticuloInformeJuridicoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByExampleWithBLOBs(
			@Param("record") ArticuloInformeJuridico record,
			@Param("example") ArticuloInformeJuridicoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByExample(@Param("record") ArticuloInformeJuridico record,
			@Param("example") ArticuloInformeJuridicoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByPrimaryKeySelective(ArticuloInformeJuridico record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByPrimaryKeyWithBLOBs(ArticuloInformeJuridico record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_articulo_ij
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByPrimaryKey(ArticuloInformeJuridico record);
}