package es.aalvarez.modelica.service;

import es.aalvarez.modelica.model.ExpedienteRelacionado;
import es.aalvarez.modelica.model.ExpedienteRelacionadoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpedienteRelacionadoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_exprelacionados
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int countByExample(ExpedienteRelacionadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_exprelacionados
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int deleteByExample(ExpedienteRelacionadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_exprelacionados
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int deleteByPrimaryKey(Integer idrelacion);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_exprelacionados
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int insert(ExpedienteRelacionado record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_exprelacionados
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int insertSelective(ExpedienteRelacionado record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_exprelacionados
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	List<ExpedienteRelacionado> selectByExample(
			ExpedienteRelacionadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_exprelacionados
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	ExpedienteRelacionado selectByPrimaryKey(Integer idrelacion);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_exprelacionados
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByExampleSelective(@Param("record") ExpedienteRelacionado record,
			@Param("example") ExpedienteRelacionadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_exprelacionados
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByExample(@Param("record") ExpedienteRelacionado record,
			@Param("example") ExpedienteRelacionadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_exprelacionados
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByPrimaryKeySelective(ExpedienteRelacionado record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_exprelacionados
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByPrimaryKey(ExpedienteRelacionado record);
}