package es.aalvarez.modelica.service;

import es.aalvarez.modelica.model.Expediente;
import es.aalvarez.modelica.model.ExpedienteExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpedienteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int countByExample(ExpedienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int deleteByExample(ExpedienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int insert(Expediente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int insertSelective(Expediente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	List<Expediente> selectByExampleWithBLOBs(ExpedienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	List<Expediente> selectByExample(ExpedienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	Expediente selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByExampleSelective(@Param("record") Expediente record,
			@Param("example") ExpedienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") Expediente record,
			@Param("example") ExpedienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByExample(@Param("record") Expediente record,
			@Param("example") ExpedienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByPrimaryKeySelective(Expediente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByPrimaryKeyWithBLOBs(Expediente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_expediente
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByPrimaryKey(Expediente record);
}