package es.aalvarez.modelica.service;

import es.aalvarez.modelica.model.TramiteActivoXExpediente;
import es.aalvarez.modelica.model.TramiteActivoXExpedienteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TramiteActivoXExpedienteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int countByExample(TramiteActivoXExpedienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int deleteByExample(TramiteActivoXExpedienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int insert(TramiteActivoXExpediente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int insertSelective(TramiteActivoXExpediente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	List<TramiteActivoXExpediente> selectByExample(
			TramiteActivoXExpedienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByExampleSelective(
			@Param("record") TramiteActivoXExpediente record,
			@Param("example") TramiteActivoXExpedienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table modlic_traxexpedienteview
	 * @mbggenerated  Fri Jan 22 20:29:47 CET 2016
	 */
	int updateByExample(@Param("record") TramiteActivoXExpediente record,
			@Param("example") TramiteActivoXExpedienteExample example);
}